### PR TITLE
Adding const qualifiers to many functions

### PR DESCRIPTION
**Pull request by msoucy**
@denizzzka, how's this look for #36 ?

### CODE REVIEW

**Comment by denizzzka** [comment]
Porbably, nothing changed:

"pb" is struct generated by dproto from .proto file:

```d
alias PubKey = ubyte[33];

PubKey pubKey(in PubKey pk) { pb.pubKey = pk /*.dup*/; return pk; }
```
```
source/ecdsa.d(28): Error: cannot implicitly convert expression (pk) of type const(ubyte[33]) to RequiredBuffer!(2LU, "bytes", ubyte[], false)
```

But if "pk" isn't const and no .dup has been used pb.pubKey will contain wrong value. I.e., dproto wants mutable value, prepared individually for it? I do not understand what's the problem.

**Comment by denizzzka** [comment]
theoretically deserialize(..) can use const value too?

**Comment by msoucy** [comment]
I don't believe that it can, since it needs the input range by reference so that it has the proper state after it finishes deserializing a field.

**Comment by denizzzka** [comment]
Range wrapper around ubyte[] ?
I just think that if the original array of ubyte[] is not changed by deserialize it is necessary to const modifier on it for safety

**Comment by msoucy** [comment]
I disagree, I feel that if you're passing an array into an algorithm that's known to consume a range, you should expect the array to be changed afterward.

**Comment by denizzzka** [comment]
Maybe two deserialize(..)? One (public) consumes const ubyte[] and one consumes range with const ubyte[] inside it?

**Comment by msoucy** [comment]
The "range with `const ubyte[]` inside it" can be mimicked with `Person p = Person(serialized_data[]);`, any reason this isn't sufficient?

**Comment by denizzzka** [comment]
Ok, I am agree with you

**Comment by denizzzka** [comment]
What can be done with it?
https://github.com/msoucy/dproto/pull/51#issuecomment-102297955

**Comment by msoucy** [comment]
Isn't that the same issue that you'd experience when assigning to a slice?

**Comment by denizzzka** [comment]
no, slicing trouble is another problem

**Comment by denizzzka** [comment]
Should I am put it into different issue ticket?

**Comment by msoucy** [comment]
I believe so

**Comment by msoucy** [comment]
I'll wait until tomorrow to merge this, just in case anyone finds any issues that this causes.

**Comment by msoucy** [comment]
More than a day, thanks real world... <_<

**Pull request merged**
